### ISSUE TITLE
Suggestions: Changed TItle color

### ISSUE THREAD

**Issue by AritraDeb-1111** [aritra-deb/github_crash-course#1]
Changed the title color, I think this looks way better.

```css
h1 {
  color: #fca714;
}
```
